// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIg82p6SA923dJCQJf4c5ZjADUS8pVsY',
    appId: '1:866485633662:web:1c5d7e01708aa0c3e44e2f',
    messagingSenderId: '866485633662',
    projectId: 'ternak-uang-3adfc',
    authDomain: 'ternak-uang-3adfc.firebaseapp.com',
    storageBucket: 'ternak-uang-3adfc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KgUPBlapJpE1zukuGSE_hoMc_HNNy2M',
    appId: '1:866485633662:android:b054af8a2624434be44e2f',
    messagingSenderId: '866485633662',
    projectId: 'ternak-uang-3adfc',
    storageBucket: 'ternak-uang-3adfc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbIg82p6SA923dJCQJf4c5ZjADUS8pVsY',
    appId: '1:866485633662:web:614f5e7ca0f173fce44e2f',
    messagingSenderId: '866485633662',
    projectId: 'ternak-uang-3adfc',
    authDomain: 'ternak-uang-3adfc.firebaseapp.com',
    storageBucket: 'ternak-uang-3adfc.appspot.com',
  );

}